// <auto-generated />
namespace WebApplication15.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class f41 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(f41));
        
        string IMigrationMetadata.Id
        {
            get { return "202204261248253_f41"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
